module.exports = {
  categories: [
    { "title": "Afghan" },
    { "title": "African" },
    { "title": "American (New)" },
    { "title": "American (Traditional)" },
    { "title": "Arabian" },
    { "title": "Argentine" },
    { "title": "Armenian" },
    { "title": "Asian Fusion" },
    { "title": "Australian" },
    { "title": "Austrian" },
    { "title": "Bangladeshi" },
    { "title": "Barbeque" },
    { "title": "Basque" },
    { "title": "Belgian" },
    { "title": "Brasseries" },
    { "title": "Brazilian" },
    { "title": "Breakfast & Brunch" },
    { "title": "British" },
    { "title": "Buffets" },
    { "title": "Burgers" },
    { "title": "Burmese" },
    { "title": "Cafes" },
    { "title": "Cafeteria" },
    { "title": "Cajun/Creole" },
    { "title": "Cambodian" },
    { "title": "Caribbean" },
    { "title": "Catalan" },
    { "title": "Cheesesteaks" },
    { "title": "Chicken Shop" },
    { "title": "Chicken Wings" },
    { "title": "Chinese" },
    { "title": "Comfort Food" },
    { "title": "Creperies" },
    { "title": "Cuban" },
    { "title": "Czech" },
    { "title": "Delis" },
    { "title": "Diners" },
    { "title": "Dinner Theater" },
    { "title": "Ethiopian" },
    { "title": "Fast Food" },
    { "title": "Filipino" },
    { "title": "Fish & Chips" },
    { "title": "Fondue" },
    { "title": "Food Court" },
    { "title": "Food Stands" },
    { "title": "French" },
    { "title": "Game Meat" },
    { "title": "Gastropubs" },
    { "title": "German" },
    { "title": "Gluten-Free" },
    { "title": "Greek" },
    { "title": "Guamanian" },
    { "title": "Halal" },
    { "title": "Hawaiian" },
    { "title": "Himalayan/Nepalese" },
    { "title": "Honduran" },
    { "title": "Hong Kong Style Cafe" },
    { "title": "Hot Dogs" },
    { "title": "Hot Pot" },
    { "title": "Hungarian" },
    { "title": "Iberian" },
    { "title": "Indian" },
    { "title": "Indonesian" },
    { "title": "Irish" },
    { "title": "Italian" },
    { "title": "Japanese" },
    { "title": "Kebab" },
    { "title": "Korean" },
    { "title": "Kosher" },
    { "title": "Laotian" },
    { "title": "Latin American" },
    { "title": "Live/Raw Food" },
    { "title": "Malaysian" },
    { "title": "Mediterranean" },
    { "title": "Mexican" },
    { "title": "Middle Eastern" },
    { "title": "Modern European" },
    { "title": "Mongolian" },
    { "title": "Moroccan" },
    { "title": "New Mexican Cuisine" },
    { "title": "Nicaraguan" },
    { "title": "Noodles" },
    { "title": "Pakistani" },
    { "title": "Pan Asian" },
    { "title": "Persian/Iranian" },
    { "title": "Peruvian" },
    { "title": "Pizza" },
    { "title": "Polish" },
    { "title": "Pop-Up Restaurants" },
    { "title": "Portuguese" },
    { "title": "Poutineries" },
    { "title": "Russian" },
    { "title": "Salad" },
    { "title": "Sandwiches" },
    { "title": "Scandinavian" },
    { "title": "Scottish" },
    { "title": "Seafood" },
    { "title": "Singaporean" },
    { "title": "Slovakian" },
    { "title": "Soul Food" },
    { "title": "Soup"},
    { "title": "Southern" },
    { "title": "Spanish" },
    { "title": "Sri Lankan" },
    { "title": "Steakhouses" },
    { "title": "Supper Clubs" },
    { "title": "Sushi Bars" },
    { "title": "Syrian" },
    { "title": "Taiwanese" },
    { "title": "Tapas Bars" },
    { "title": "Tapas/Small Plates" },
    { "title": "Tex-Mex" },
    { "title": "Thai"},
    { "title": "Turkish" },
    { "title": "Ukrainian" },
    { "title": "Uzbek" },
    { "title": "Vegan" },
    { "title": "Vegetarian" },
    { "title": "Vietnamese" },
    { "title": "Waffles" },
    { "title": "Wraps" }
  ]
}